keyword_lcurly : LCURLY
<<0
symtab=SymbolTable()
key = "sym#" + str(p.lexer.lineno) + "#" + str(p.lexer.lexpos)
symTableDict[key] = symtab
symTableSt += [key]
>>

keyword_rcurly : RCURLY
<<0
symTableSt = symTableSt[:-1]
>>

SourceFile  : PackageClause ImportDeclList
<<0
rootSym = symTableDict['rootSymTable']
for s in rootSym.symbols:
        print(vars(rootSym.symbols[s]))
>>

PackageClause  : PACKAGE IDENTIFIER
<<0
scope = symTableSt[-1]
symTable = symTableDict[scope]
pkg = PackageEntry(p[2])
symTable.put(pkg)
>>

ImportDeclList : ImportDecl ImportDeclList
               | empty

ImportDecl    : IMPORT ImportSpecTopList

ImportSpecTopList : ImportSpec
                  | LPAREN ImportSpecList RPAREN

ImportSpecList : ImportSpec ImportSpecList
               | empty

ImportSpec       :  ImportSpecInit ImportPath

ImportSpecInit : DOT
               | IDENTIFIER
               | empty

ImportPath     : STRINGLIT
<<0
scope = symTableSt[-1]
symTable = symTableDict[scope]
lit = LitEntry(p[1], p[1])
symTable.put(lit)
>>