Start : PackageClause ImportDeclList

PackageClause  : keyword_package PackageName

PackageName    : IDENTIFIER

keyword_package : PACKAGE

ImportDeclList : empty
               | ImportDeclList ImportDecl

ImportDecl     : keyword_import ImportSpec
               | keyword_import left_paren ImportList right_paren

keyword_import : IMPORT

left_paren     : LPAREN

ImportList     : empty
               | ImportList ImportSpec

ImportSpec     : ImportPath
               | dot ImportPath
               | PackageName ImportPath

ImportPath     : string_literal

dot     : DOT

string_literal    : STRINGLIT

right_paren     : RPAREN