keyword_package : PACKAGE

keyword_identifier : IDENTIFIER

keyword_import : IMPORT

keyword_lparen : LPAREN

keyword_rparen : RPAREN

keyword_dot : DOT

SourceFile    : PackageClause ImportDeclList

PackageClause  : keyword_package keyword_identifier

ImportDeclList : ImportDecl ImportDeclList
               | empty

TopLevelDeclList : STRINGLIT TopLevelDeclList
                 | empty

ImportDecl    : keyword_import ImportSpecTopList

ImportSpecTopList : ImportSpec
                  | keyword_lparen ImportSpecList keyword_rparen 

ImportSpecList : ImportSpec ImportSpecList
               | empty

ImportSpec       :  ImportSpecInit ImportPath

ImportSpecInit : keyword_dot
               | keyword_identifier
               | empty

ImportPath     : STRINGLIT