Expression : UnaryExpr
           | Expression binary_op Expression
           | IDENTIFIER DOT IDENTIFIER
           | IDENTIFIER keyword_lcurly ObjectParamList keyword_rcurly
<<1
p[0]['code'] =p[1]['code']
p[0]['place'] = p[1]['place']
>>
<<4
p[0]['place'] = newVar()
p[0]['code'] = [p[0]['place'] + ':=' + p[1]['place'] + '.' + p[2]['place']]
>>